### ISSUE TITLE
«Argument 1 passed to Magento\Catalog\Model\Category\FileInfo::removeStorePath() must be of the type string, array given, called in vendor/magento/module-catalog/Model/Category/FileInfo.php on line 167»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [vegandthecity/magento#33]

**Comment by dmitrii-fediuk** [comment]
I have implemented a logging in `vendor/magento/module-catalog/Model/Category/FileInfo.php`.

**Comment by JamesX88** [comment]
Did you figure this out @dmitry-fedyuk ?

**Comment by andres2392** [comment]
any luck with this issue?

**Comment by dmitrii-fediuk** [comment]
Currently, I do not work on the [vegandthecity.ch/shop](https://vegandthecity.ch/shop) project.  
You can hire me in Upwork to analyze and solve the issue in your store: [upwork.com/fl/mage2pro](https://www.upwork.com/fl/mage2pro)

**Comment by CyanoCore** [comment]
Any updates on the issue?

**Comment by dmitrii-fediuk** [comment]
I work in Upwork only and do not work with anyupdaters.

**Comment by Asitis** [comment]
Why then open an issue if you're not willing to update anything or anyone about it. Certainly not about to hire someone with that attitude..

**Comment by dmitrii-fediuk** [comment]
OK, the next anyupdater without money is banned.

**Comment by roshanyadav89** [comment]
@Asitis  Absolutely correct but still any update on this? :)

**Comment by Brocknoviatch** [comment]
I got this error when I had two categories with the same name. By changing the name, on one of the categories, I fixed the error.

**Comment by jimses** [comment]
This is one of the stranger tickets I've read.

**Comment by stkrelax** [comment]
this actually only happens when validate function returns an error
